### ISSUE TITLE
Поддержка Laravel 5.2

### ISSUE THREAD

**Issue by pwnz22** [CawaKharkov/yandex-kassa#1]
Добрый день!

Этот пакет можно использовать с Laravel 5.2? 

Я установил пакет, сделал php artisan vendor:publish, но конфиги не появились.

**Comment by cawa87** [comment]
Добрый, проверю

**Comment by cawa87** [comment]
А ты уверен что добавил все сервис провайдеры в `confg/app.php`?

**Comment by pwnz22** [comment]
Ох, извиняйте. Забыл добавить, но у меня все равно ошибки в миграциях, похоже что баланс нужно установить сначала а мне нужна только для транзакций. В Laravel недавно, Придется покопаться. 
Спасибо за помощь.

**Comment by cawa87** [comment]
Прошу почитать доку к зависимому пакету. Баланс = сумма транзакций. Пакет [CawaKharkov/laravel-balance](https://github.com/CawaKharkov/laravel-balance) реализует именно транзакции и отвечает за баланс,, а этот пакет реализует метод пополнения.

**Comment by cawa87** [comment]
Под Laravel 5.2 будет отдельная ветка, так некоторые вещи не совместимы с 5.3
