### ISSUE TITLE
Ошибка добавления данных в таблицу yandex_payments

### ISSUE THREAD

**Issue by Gesparo** [CawaKharkov/yandex-kassa#2]
Добрый день. Столкнулся с такой проблемой. При добавлении данных в таблицу yandex_payments посредством YandexPaymentRepositoryInterface ругается на поле 'type'

`Next Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'type' in 'field list' (SQL: insert into `yandex_payments` (`orderSumAmount`, `type`, `action`, `invoiceId`, `shopSumAmount`, `hash`, `user_id`, `transaction_id`, `updated_at`, `created_at`) values (1200.00, AC, checkOrder, 'xxxxxxxxxxxxxxxxxxxxx', 1158.00, yandex_payment_xxxxxxx, 1, 4, 2017-04-18 09:45:30, 2017-04-18 09:45:30)) in /var/www/gesparo/data/www/site.xxxxxxx.ru/vendor/laravel/framework/src/Illuminate/Database/Connection.php:647
`

Проблема заключается в том, что в модели YandexPayment.php в переменной $fillable есть поле 'type', которое соответственно можно заполнить. Но в миграции 2016_05_07_081647_create_yandex_payment.php этого поля нет. 

Так что прошу вас либо убрать это поле с модели, либо добавить это поле в миграцию.

P.S. Чтобы не лезть в документацию, сказу что поле 'type' есть в запросе от Яндекса и оно хранит в себе тип оплаты(т.е. как платил клиент - банковской картой или чем то еще)

**Comment by cawa87** [comment]
Спасибо, добавил.

**Comment by Gesparo** [comment]
Не за что

**Comment by Gesparo** [comment]
Может я что то неправильно понимаю, но разве он хранит integer? От Яндекса пришел запрос и в поле type указан AC - что означает - оплата банковской картой. И я действительно платил картой. И это поле текстовое. 

https://tech.yandex.ru/money/doc/payment-solution/reference/payment-type-codes-docpage/

**Comment by cawa87** [comment]
Странно, мне почему-то казалось они шлют инт, поменял.
